import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "./providers";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DEAC E-sport",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: {children: React.ReactNode;}) {
  return (
    <html lang="en" suppressHydrationWarning className={cn("font-sans", inter.variable)}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen w-full bg-white opacity-100 
      bg-[radial-gradient(#e9e8e8_1.05px,#ffffff_1.05px)] bg-size-[21px_21px]
      dark:bg-black dark:bg-[radial-gradient(#1c1c1c_1.05px,#121212_1.05px)]`}>
        <Providers>
          <Navbar />
          <div className="px-60 min-h-156">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}